[[headers]]
  for = "/*"
  [headers.values]
    cache-control = '''
      max-age=0,
      no-cache,
      no-store,
      must-revalidate
    '''
    Content-Security-Policy = '''
      default-src 'self' https://*.lunie.io https://*.netlify.app https://www.google-analytics.com https://monitoring.lunie.io:9000 https://js.intercomcdn.com;
      connect-src 'self' https://api-iam.intercom.io https://widget.intercom.io wss://production-api.lunie.io/graphql https://production-api.lunie.io https://monitoring.lunie.io:9000 wss://kusama-rpc.polkadot.io/ wss://lunie-wss.kusama.fish;
      img-src 'self' data: https://*.lunie.io https://*.netlify.app https://www.google-analytics.com https://s3.amazonaws.com https://lunie.fra1.digitaloceanspaces.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.lunie.io https://*.netlify.app https://www.google-analytics.com https://api-iam.intercom.io https://js.intercomcdn.com https://widget.intercom.io;
      style-src 'self' 'unsafe-inline' https://*.lunie.io https://*.netlify.app;
      media-src 'self' https://*.lunie.io https://*.netlify.app blob:;
      object-src 'self' data: blob: https://*.lunie.io https://*.netlify.app https://www.google-analytics.com;
      manifest-src 'self' https://*.lunie.io https://*.netlify.app;
      worker-src 'none';
      frame-src 'self' https://api-iam.intercom.io https://widget.intercom.io;
      frame-ancestors 'self';
      base-uri 'self';
      font-src 'self' data: https://js.intercomcdn.com;
    '''
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"

[context.production]
  command = "yarn buildsentry"

[context.deploy-preview]
  command = "yarn build --mode development"

[context.deploy-preview.environment]
  SENTRY_DSN = ""
  SENTRY_URL = ""
  SENTRY_TOKEN = ""

[context.deploy-preview.processing]
  skip_processing = true