name: Update existing droplet in Digital Ocean

on:
  pull_request:
    branches:
      - 'master'
    paths:
      - 'api/CHANGELOG.md'
env:
  WORKING_DIRECTORY: ./api
  HASURA_URL: "https://production-db.lunie.io/v1/graphql"
  HASURA_ADMIN_KEY: ${{ secrets.LUNIE_PRODUCTION_DB_KEY }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN_API_PRODUCTION }}
jobs:
  test:
    name: Compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
    - uses: bahmutov/npm-install@v1
      with:
        working-directory: ${{env.WORKING_DIRECTORY}}
    - name: Build image
      run: docker build -t lunieapi . 
      working-directory: ${{env.WORKING_DIRECTORY}}
    - name: Save file
      run: docker save lunieapi | gzip > lunieapi.tgz
      working-directory: ${{env.WORKING_DIRECTORY}}
    - name: Copy file via scp
      uses: appleboy/scp-action@master
      with:
        source: "api/lunieapi.tgz,api/docker-compose.yml,api/Caddyfile"
        target: "/root/"
        host: ${{ secrets.HOST_PRODUCTION }}
        username: root
        # key: ${{ secrets.DO_PRIVATE_KEY }}
        password: ${{ secrets.PRODUCTION_PASSWORD }}
    - name: Install on instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_PRODUCTION }}
        username: root
        password: ${{ secrets.PRODUCTION_PASSWORD }}
        script: |
          sudo curl -L \"https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker image prune -a -f
          docker load < lunieapi.tgz
          docker stack deploy -c docker-compose.yml lunieapi
          docker service update --image lunieapi:latest --force lunieapi_lunieapi
        envs: HASURA_URL,HASURA_ADMIN_KEY,SENTRY_DSN