name: App testing

on:
  pull_request:
    branches:
      - "*"
    paths:
      - 'app/**'
env:
  WORKING_DIRECTORY: ./app
  VUE_APP_FIREBASE_CONFIG: ${{ secrets.VUE_APP_FIREBASE_CONFIG }}
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - uses: bahmutov/npm-install@v1.1.0
      - name: Test
        run: |
          yarn test:unit --coverage
          bash <(curl -s https://codecov.io/bash)
        working-directory: ${{env.WORKING_DIRECTORY}}
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - uses: bahmutov/npm-install@v1.1.0
      - name: Lint
        run: yarn lint 
        working-directory: ${{env.WORKING_DIRECTORY}}
  checkChangelog:
    name: checkChangelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Check if changelog was updated
        run: npx simsala check --pending-path ./app/changes
