name: Extension testing

on:
  pull_request:
    branches:
      - "*"
    paths:
      - 'extension/**'
env:
  WORKING_DIRECTORY: ./extension
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{env.WORKING_DIRECTORY}}
      - name: Test
        run: |
          yarn test:unit --coverage
          bash <(curl -s https://codecov.io/bash)
        working-directory: ${{env.WORKING_DIRECTORY}}
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{env.WORKING_DIRECTORY}}
      - name: Lint
        run: yarn lint 
        working-directory: ${{env.WORKING_DIRECTORY}}
  checkChangelog:
    name: checkChangelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Check if changlog was updated
        run: npx simsala check --pending-path ./changes
        working-directory: ${{env.WORKING_DIRECTORY}}
