name: Extension publishing

on:
  push:
    branches:
      - "master"
    paths:
      - 'extension/*'
env:
  WORKING_DIRECTORY: ./extension
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - uses: bahmutov/npm-install@v1
      - name: Build
        run: LUNIE_API=${{ secrets.LUNIE_API }} yarn build
        working-directory: ${{env.WORKING_DIRECTORY}}
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN_EXTENSION }}
      - name: Zip
        run: yarn build-zip
        working-directory: ${{env.WORKING_DIRECTORY}}
      - name: Deploy
        run: sh ./scripts/deploy.sh ./dist-zip/extension.zip
        working-directory: ${{env.WORKING_DIRECTORY}}
        env:
          GAPI_CLIENT_ID: ${{ secrets.GAPI_CLIENT_ID }}
          GAPI_CLIENT_SECRET: ${{ secrets.GAPI_CLIENT_SECRET }}
          GAPI_REFRESH_TOKEN: ${{ secrets.GAPI_REFRESH_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.GAPI_ACCESS_TOKEN }}
          APP_ID: ${{ secrets.EXTENSION_APP_ID }}
