name: Publish to master

on:
  push:
    branches:
      - develop
    paths:
      - 'api/CHANGELOG.md'
      - 'app/CHANGELOG.md'
      - 'extension/CHANGELOG.md'
      - 'scriptRunner/CHANGELOG.md'

env:
    GIT_BOT_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}
jobs:
    publish:
        name: publish
        runs-on: ubuntu-latest
        timeout-minutes: 3
        steps:
        - uses: actions/checkout@v1
        - name: Use Node.js
          uses: actions/setup-node@v1
        - name: publish to master
          run: bash ./scripts/publish.sh        