name: Create a release PR

on:
  push:
    branches:
      - release
jobs:
  createReleasePR:
    name: createReleasePR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@master
    - name: yarn install
      run: yarn && yarn add simsala
    - name: configure release bot
      run: git config user.email "bot@lunie.io" && git config user.name "Release Lunie Bot"
    - name: use ssh repo
      run: git config user.email "bot@lunie.io" && git config user.name "Release Lunie Bot"
    - name: create release PR
      run: node node_modules/simsala/src/cli.js release-candidate --semver patch --pending-path ./changes --owner luniehq --repository lunie --token ${{ secrets.GIT_BOT_TOKEN }} --message "Please manually test before merging this to master"
